### ISSUE TITLE
File not uploading to tg

### ISSUE THREAD

**Issue by Geoteser** [5MysterySD/Tele-LeechX#16]
2022-07-24T07:26:19.374160+00:00 app[worker.1]: 24-Jul-22 12:56:19 - INFO - ✅ <i>Downloaded Successfully</i> ✅: `bridge.and.tunnel.s02e03.720p.web.hevc.x265.rmteam.mkv (131.47 MiB)`  [download_aria_p_n.py:363]
2022-07-24T07:26:20.768715+00:00 app[worker.1]: 24-Jul-22 12:56:20 - DEBUG - Initializing backend: Total rows: 1 responses, 0 redirects /app/.lk21-requests-cache [__init__.py:76]
2022-07-24T07:26:20.770433+00:00 app[worker.1]: 24-Jul-22 12:56:20 - DEBUG - Cache directives from request headers: {} [cache_control.py:86]
2022-07-24T07:26:20.773224+00:00 app[worker.1]: 24-Jul-22 12:56:20 - DEBUG - Pre-cache checks for response from http://localhost:6800/jsonrpc: {'disabled cache': False, 'disabled method': True, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False} [session.py:173]
2022-07-24T07:26:20.773370+00:00 app[worker.1]: 24-Jul-22 12:56:20 - DEBUG - Skipping cache write for URL: http://localhost:6800/jsonrpc [session.py:197]
2022-07-24T07:26:20.773903+00:00 app[worker.1]: 24-Jul-22 12:56:20 - INFO -  Zip : False [download_aria_p_n.py:250]
2022-07-24T07:26:20.774028+00:00 app[worker.1]: 24-Jul-22 12:56:20 - INFO -  UnZip : False [download_aria_p_n.py:251]
2022-07-24T07:26:20.774275+00:00 app[worker.1]: 24-Jul-22 12:56:20 - INFO - Files Less Than 2 GB [upload_to_tg.py:185]
2022-07-24T07:26:30.776155+00:00 app[worker.1]: 24-Jul-22 12:56:30 - INFO - Found Dyanamic Config for User : 1301681265 [upload_to_tg.py:379]
2022-07-24T07:26:31.226021+00:00 app[worker.1]: 24-Jul-22 12:56:31 - INFO - Premium Active : False [upload_to_tg.py:402]
2022-07-24T07:26:31.226165+00:00 app[worker.1]: 24-Jul-22 12:56:31 - DEBUG - Entering: send_document [bot.py:132]
2022-07-24T07:26:31.247878+00:00 app[worker.1]: 24-Jul-22 12:56:31 - ERROR - Invalid file http url specified: unsupported url protocol [dispatcher.py:253]
2022-07-24T07:26:31.247880+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-24T07:26:31.247880+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2022-07-24T07:26:31.247881+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-07-24T07:26:31.247881+00:00 app[worker.1]:   File "/app/tobrot/plugins/incoming_message_fn.py", line 238, in incoming_message_f
2022-07-24T07:26:31.247882+00:00 app[worker.1]:     sagtus, err_message = await call_apropriate_function(
2022-07-24T07:26:31.247882+00:00 app[worker.1]:   File "/app/tobrot/helper_funcs/download_aria_p_n.py", line 303, in call_apropriate_function
2022-07-24T07:26:31.247883+00:00 app[worker.1]:     final_response = await upload_to_tg(
2022-07-24T07:26:31.247884+00:00 app[worker.1]:   File "/app/tobrot/helper_funcs/upload_to_tg.py", line 186, in upload_to_tg
2022-07-24T07:26:31.247884+00:00 app[worker.1]:     sent_message = await upload_single_file(
2022-07-24T07:26:31.247884+00:00 app[worker.1]:   File "/app/tobrot/helper_funcs/upload_to_tg.py", line 459, in upload_single_file
2022-07-24T07:26:31.247885+00:00 app[worker.1]:     sent_message = await bot.send_document(
2022-07-24T07:26:31.247885+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 133, in decorator
2022-07-24T07:26:31.247886+00:00 app[worker.1]:     result = func(*args, **kwargs)
2022-07-24T07:26:31.247886+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 976, in send_document
2022-07-24T07:26:31.247886+00:00 app[worker.1]:     return self._message(  # type: ignore[return-value]
2022-07-24T07:26:31.247887+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/ext/extbot.py", line 202, in _message
2022-07-24T07:26:31.247888+00:00 app[worker.1]:     result = super()._message(
2022-07-24T07:26:31.247888+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 339, in _message
2022-07-24T07:26:31.247888+00:00 app[worker.1]:     result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
2022-07-24T07:26:31.247889+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 298, in _post
2022-07-24T07:26:31.247889+00:00 app[worker.1]:     return self.request.post(
2022-07-24T07:26:31.247889+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/utils/request.py", line 361, in post
2022-07-24T07:26:31.247890+00:00 app[worker.1]:     result = self._request_wrapper(
2022-07-24T07:26:31.247890+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/utils/request.py", line 279, in _request_wrapper
2022-07-24T07:26:31.247891+00:00 app[worker.1]:     raise BadRequest(message)
2022-07-24T07:26:31.247891+00:00 app[worker.1]: telegram.error.BadRequest: Invalid file http url specified: unsupported url protocol
 Autoscroll with outputSave
heroku.com
Blogs
Careers
Documentation

**Comment by 5MysterySD** [comment]
**Guideline for Fix :**
- Issue Fixed Temporary, Don't Put EXCEP_CHATS var 
- Update your Bot By Simply Restarting your bot with Main UPSTREAM_REPO 
- Any Questions : Join Telegram Channel [@FXTorrentz](https://t.me/FXTorrentz)

**Comment by Geoteser** [comment]
Thanks. Working well😇
