### ISSUE TITLE
RCLONE COMMAND NOT WORKING ERROR

### ISSUE THREAD

**Issue by assc0d3r** [5MysterySD/Tele-LeechX#19]
2022-07-25T13:25:26.121024+00:00 app[worker.1]: 25-Jul-22 06:55:26 PM - pyrogram.dispatcher - ERROR - name 'pyrogram' is not defined [dispatcher.py:253]
2022-07-25T13:25:26.121025+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-25T13:25:26.121025+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2022-07-25T13:25:26.121026+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-07-25T13:25:26.121026+00:00 app[worker.1]:   File "/app/tobrot/plugins/choose_rclone_config.py", line 47, in rclone_command_f
2022-07-25T13:25:26.121027+00:00 app[worker.1]:     reply_markup = pyrogram.InlineKeyboardMarkup(inline_keyboard)
2022-07-25T13:25:26.121027+00:00 app[worker.1]: NameError: name 'pyrogram' is not defined

**Comment by 5MysterySD** [comment]
**Guidelines : [ Bug Fixed ] **
- Update your Bot By Simply Restarting your bot with Main UPSTREAM_REPO
- Any Questions : Join Telegram DeBug Group
